// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"maxblog-be-template/internal/core"
	"maxblog-be-template/src/model"
	"maxblog-be-template/src/service"
)

// Injectors from wire.go:

func InitInjector() (*Injector, func(), error) {
	db, cleanup, err := InitDB()
	if err != nil {
		return nil, nil, err
	}
	mData := &model.MData{
		DB: db,
	}
	trans := &core.Trans{
		DB: db,
	}
	logger := &core.Logger{}
	bData := &service.BData{
		MData:   mData,
		Tx:      trans,
		ILogger: logger,
	}
	injector := &Injector{
		DB:      db,
		Service: bData,
	}
	return injector, func() {
		cleanup()
	}, nil
}
